CarnivalProject/CarnivalProject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    #url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    #url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^messageService/', include('messageService.urls', namespace='messageService')),
    url(r'^admin/', admin.site.urls),
]

CarnivalProject/accounts/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'signup/$',views.SignUpView.as_view(), name='signup'),
    url(r'manageaccount/$', views.manage_account, name='manageAccount'),
]

CarnivalProject/templates/index.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}Book Store {% endblock %}


{% block content %}

    <header class="jumbotron">
        <div class="container">
            <div class="row row-header">
                <div class="col-xs-12 col-sm-8">
                    <h1><font face="Century Gothic" size="25"><center><b>Welcome to Your One Stop Shop for All Things Literature</b></center></font></h1>
                    <p style="padding:20px;"></p>
                    <p><font face="Century Gothic" size="4"><center>The best book store in your city, selling the best in Tech and Sci Fi books with
                    amazing prices</center></font></p>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <img class="img-responsive" src="{% static 'img/stackbook.png' %}">
                </div>
            </div>
        </div>
    </header>

<center><h3><font face="Century Gothic" size="7">Why You Should Buy With Bard</font></h3></center>

<section class="reasons-why">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="glyphicon glyphicon-book glyphicon-large" aria-hidden="true"></span>
        <h3>Tons of Books!</h3>
        <p>Bard's Big Bad Bookstore hosts one of the largest collections of books in the world.
        All at your fingertips.</p>
      </div>
      <div class="col-md-4">
        <span class="glyphicon glyphicon-flash glyphicon-large" aria-hidden="true"></span>
        <h3>Speedy Service!</h3>
        <p>All of our orders are delivered quickly and safely, because customer satisfaction is always our number one priority.</p>
      </div>
      <div class="col-md-4">
        <span class="glyphicon glyphicon-heart-empty glyphicon-large" aria-hidden="true"></span>
        <h3>Passion for Literature!</h3>
        <p>Everyone behind Bard's Big Bad Bookstore is a nut for books! We want to share with the world what we love the most, and won't
        stop until literature is accessible to all!</p>
      </div>
    </div>
  </div>
</section>

<hr width="1500">


<h2><font face="Century Gothic" size="6"><center>Take a look at some of our shop's accolades!</center></font></h2>
&nbsp;

    <div class="container">
        <div class="carousel slide" data-ride="carousel" id="bookSlides" style="width: 600px; margin: auto">
            <ol class="carousel-indicators">
                <li data-target="#bookSlides" data-slide-to="0" class="active"></li>
                <li data-target="#bookSlides" data-slide-to="1"></li>
                <li data-target="#bookSlides" data-slide-to="2"></li>
            </ol>

            <div class="carousel-inner">

                <div class="item active pic">
                    <img class="img-responsive" src="{% static 'img/design.png' %}" alt="image" style="width:auto; height:500px;">
                    <div class="carousel-caption">
                        <h2>Junior Design Award 2016</h2>
                    </div>
                </div>

                <div class="item pic">
                    <img class="img-responsive" src="{% static 'img/best2016.png' %}" alt="image" style="width:auto; height:500px;">

                    <div class="carousel-caption">
                        <h2>The Best of 2016 Award</h2>
                    </div>
                </div>

                <div class="item pic">
                    <img class="img-responsive" src="{% static 'img/investor.png' %}" alt="image" style="width:auto; height:500px;">

                    <div class="carousel-caption">
                        <h2>The Investors in People Award 2016</h2>
                    </div>
                </div>
            </div>

            <a href="#bookSlides" class="left carousel-control" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a href="#bookSlides" class="right carousel-control" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>

    <div>
        <p style="padding:25px"></p>
    </div>

{% endblock %}

CarnivalProject/templates/layout.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width , initial-scale=1">
    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="{% static 'css/mystyles.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap-social.css' %}" rel="stylesheet" type="text/css">
    <style>
        .fieldSizeFont{
            font-size:17px;
            font-family:arial;
        }
    </style>
</head>


<body style="background-color: aliceblue">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

        <div class="container">
            <div class="navbar-header" style="height:100px;">
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse"
                        data-target="#navbarTop" aria-controls="navbar" aria-expanded="false">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img src="{% static 'img/homelogo.png' %}"
                                                      class="result" height="80" width="300"></a>
            </div>

            <div class="navbar-collapse collapse" id="navbarTop">
                <ul class="nav navbar-nav navbar-center">
                </ul>

            </div>

            <div class="navbar-header">
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse"
                        data-target="#navbar" aria-controls="navbar" aria-expanded="false">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="navbar-collapse collapse" id="navbar">
                <ul class="nav navbar-nav">

                    <!-- Link to Home page -->
                    <li>
                        <a style="color: white" class="navTabColor" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">

                    {% if user.is_authenticated %}
                    <li>
                    </li>
                    {% else %}
                    <li>
                        <!-- Login id target -->
                        <a style="color: white" href="#" class="nav-link" data-toggle="modal" data-target="#modalSignIn">Sign In</a>
                    </li>
                    {% endif %}

                    {% if user.is_authenticated %}
                    <!-- Link to Dropdown for My Account -->
                    <li class="dropdown"><a style="color: white" class="dropdown-toggle" data-toggle="dropdown" role="button"
                            href="" aria-haspopup="true" aria-expanded="false">My Account<span class="caret"></span>
                    </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'accounts:manageAccount' %}">Manage Account</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li>
                        <a style="color: white" href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% block content %}{% endblock %}

     <!-- Sign In Modal -->
    <div class="modal fade" id="modalSignIn" role="dialog">
        <div class="modal-dialog">
            <!-- Sign In Modal Content -->
            <div class="modal-content">
                {% include 'accounts/login.html' %}
            </div>
        </div>
    </div>

    <!-- Footer with contact information -->
    <footer class="row-footer" >
        <div class="container">
            <div class="'row ">
                <div class="col-xs-5 col-xs-offset-1 col-sm-2 col-sm-offset-1">
                    <h5>Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'index' %}">Home</a></li>
                    </ul>
                </div>
                <div class="col-xs-6 col-sm-5">
                    <h5>Our Address</h5>
                    <address>
                        6369 SW 173rd Street<br>
                        33011<br>
                        Miami,Florida<br>
                        <i class="fa fa-phone"></i> : +305 1234 5678<br>
                        <i class="fa fa-envelope"></i> : <a href="#">BardsBigBadBS@gmail.com</a>
                    </address>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <div class="nav navbar-nav" style="padding: 40px 10px;">
                        <a class="btn btn-social-icon btn-google-plus" href="http://google.com/+">
                            <i class="fa fa-google-plus"></i></a>
                        <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id=">
                            <i class="fa fa-facebook"></i></a>
                        <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com/in/">
                            <i class="fa fa-linkedin"></i></a>
                        <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/">
                            <i class="fa fa-twitter"></i></a>
                        <a class="btn btn-social-icon btn-youtube" href="http://youtube.com/">
                            <i class="fa fa-youtube"></i></a>
                        <a class="btn btn-social-icon" href="mailto:"><i class="fa fa-envelope"></i></a>
                    </div>
                </div>
                <div class="col-xs-12">
                    <p style="padding:10px;"></p>
                    <p align=center>© Copyright 2017 Bard's Big Bad Bookstore</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- jQuery(neccessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    {% block javascript_code %} {% endblock %}

</body>
</html>