CarnivalProject/CarnivalProject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    #url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    #url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^messageService/', include('messageService.urls', namespace='messageService')),
    url(r'^admin/', admin.site.urls),
]

CarnivalProject/accounts/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'signup/$',views.SignUpView.as_view(), name='signup'),
    url(r'manageaccount/$', views.manage_account, name='manageAccount'),
]

CarnivalProject/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin
)
from django.utils import timezone

# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self,nickname,email_address,password=None):
        if not email_address:
            raise ValueError("Users must enter an email address")
        if not nickname:
            raise ValueError("Users must enter a nickname")

        user = self.model(email_address=self.normalize_email(email_address), nickname=nickname)

        user.set_password(password)
        user.save()
        return user

    def create_superuser(self,nickname,email_address,password):
        user = self.create_user(nickname,email_address,password)
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    user_id = models.AutoField(primary_key=True)
    nickname = models.CharField(unique=True, max_length=255)
    first_name = models.CharField(max_length=50, default=None , null=True)
    last_name = models.CharField(max_length=50, default=None, null=True)
    password = models.CharField(max_length=255)
    email_address = models.EmailField(unique=True, max_length=255)
    last_login = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    about_me = models.CharField(max_length =500)

    objects = UserManager()

    USERNAME_FIELD = 'nickname'

    REQUIRED_FIELDS = ['email_address', 'password']

    def __str__(self):
        return "@{}".format(self.nickname)

    def get_short_name(self):
        return self.nickname

    def get_full_name(self):
        return "{} {}".format(self.nickname, self.email_address)

    class Meta:
        managed = True
        db_table = "users"

CarnivalProject/accounts/forms.py
import re
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django import forms
from .models import User


class LoginForm(forms.Form):
    nickname = forms.CharField(required=True)
    password = forms.CharField(required=True)

    class Meta:
        fields = ('nickname', 'password')
        model = User

    def clean_nickname(self):
        nickname = self.cleaned_data['nickname']

        try:
            User.objects.get(nickname=nickname)
        except User.DoesNotExist:
            raise forms.ValidationError('Sorry that user does not exist.')

        return nickname


class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email_address = forms.EmailField(max_length=254, required=True)

    class Meta:
        fields = ("nickname", "email_address", 'first_name', 'last_name', "password1", "password2", "about_me")
        model = User

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name in ['password1', 'password2']:
            self.fields[field_name].help_text = None

        self.fields["email_address"].label = "Email Address"
        self.fields["first_name"].label = "First Name"
        self.fields["last_name"].label = "Last Name"
        self.fields["password2"].label = "Password Confirmation"
        self.fields["about_me"].label = "About Me"


    def clean_nickname(self):
        nickname = self.cleaned_data['nickname']

        if not re.search(r'^\w+$', nickname):
            raise forms.ValidationError('Nickname can only contain alphanumeric characters and underscore.')

        try:
            User.objects.get(nickname=nickname)

        except User.DoesNotExist:
            return nickname

        raise forms.ValidationError('Nickname already exists.')

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2

            raise forms.ValidationError('Password do not match!')

    def clean_email_address(self):
        email = self.cleaned_data['email_address']

        # check if email address is valid
        if not re.match('^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$', email.lower()):
            raise forms.ValidationError('Email Address is invalid format.')

        # check if email address already exits
        try:
            User.objects.get(email_address=email)
        except User.DoesNotExist:
            return email

        raise forms.ValidationError('Email Address already exists.')


class EditUserProfileForm(ModelForm):
    first_name = forms.CharField(label='First Name')
    last_name = forms.CharField(label='Last Name')
    nickname = forms.CharField(label='Nickname')
    email_address = forms.EmailField(label="Email Address")

    def clean_nickname(self):
        nickname = self.cleaned_data['nickname']

        # check if nickname submitted is the same as the current user online
        if nickname == self.instance.nickname:
            return nickname

        # username is different from previous, check if it already exists
        try:
            User.objects.exclude(pk=self.instance.user_id).get(nickname=nickname)
        except User.DoesNotExist:
            return nickname

        raise forms.ValidationError('Nickname already exists.')

    def clean_email_address(self):
        email_address = self.cleaned_data['email_address']

        # check if email address is missing
        if not email_address:
            raise forms.ValidationError('Email Address is missing.')

        # check if email address submitted is the same as the current user online
        if email_address == self.instance.email_address:
            return email_address

        # email address is different from previous, check if it already exits
        try:
            User.objects.exclude(pk=self.instance.user_id).get(email_address=email_address)
        except User.DoesNotExist:
            return email_address

        raise forms.ValidationError('Email Address already exists')

    class Meta:
        model = User
        fields = ['first_name', 'last_name','nickname','email_address']

CarnivalProject/accounts/views.py
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_protect
from django.views.generic import DeleteView, CreateView, RedirectView
from .forms import EditUserProfileForm, UserCreateForm, LoginForm
from .models import User
from django.contrib import messages


#########################################################################################################
##                                   USER FUNCTIONS                                                   ##
########################################################################################################

@csrf_protect
def login_view(request):
    next = request.POST.get('next', '/')
    form = LoginForm

    if request.method == 'POST':

        username = request.POST['nickname']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        # if we have a user object, credentials correct
        if user:
            # check to see if account is active
            if user.is_active:
                # if account is active login the user and send the user back to homepage
                login(request, user)
                current_user = request.user
            # account is not active
            else:
                messages.error(request, 'Your account has been disabled.')

        # no user with matching credentials
        else:
            # bad login credentials were provided
            messages.error(request, 'Sorry the credentials you input, were incorrect.')

        return HttpResponseRedirect(next)

@csrf_protect
def manage_account(request):
    online_user = request.user
    user = User.objects.get(pk=online_user.user_id)
    form = EditUserProfileForm(request.POST or None, initial={'first_name': online_user.first_name,
                                                    'last_name': online_user.last_name, 'nickname': online_user.nickname,
                                                    'email_address': online_user.email_address}, instance=request.user)

    if request.method == 'POST':
        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.nickname = form.cleaned_data['nickname']
            user.email_address = form.cleaned_data['email_address']

            user.save()

            messages.success(request, 'User information changes have been successfully saved.')

            return HttpResponseRedirect(reverse('index'))

    else:
        form = EditUserProfileForm(instance=online_user)

    return render(request, "accounts/manageAccount.html", {'form': form})


class SignUpView(CreateView):
    form_class = UserCreateForm
    model = User
    template_name = "accounts/signUp.html"
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        new_user = form.save()
        messages.info(self.request, 'Thanks for registering. You may now login.')

        # after the new user is created, login the user
        new_user = authenticate(username=form.cleaned_data['nickname'], password=form.cleaned_data['password1'])
        login(self.request, new_user)

        return super(SignUpView, self).form_valid(form)

class LogoutView(RedirectView):
    url = reverse_lazy("index")

    def get(self, request, *args, **kwargs):
        logout(request)
        messages.success(request, 'Successfully logged out.')
        return super().get(request, *args, **kwargs)


# Create your views here.

CarnivalProject/accounts/templates/accounts/login.html
<form class="form-horizontal" method="POST" action="{% url 'accounts:login' %}">{% csrf_token %}
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">Sign In</h3>
        </div>
        <div class="container">
            <div class="modal-body">
                <!-- Sign In form -->
                <div class="row">
                    <div class="form-group">
                        <label for="nicknameId" class="col-sm-2" >Nickname</label>
                        <input type="text" class="col-sm-3" id="nicknameId" name="nickname" placeholder="Nickname">
                    </div>
                    <div class="form-group">
                        <label for="passwordId" class="col-sm-2" >Password</label>
                        <input type="password" class="col-sm-3" id="passwordId" name="password" placeholder="Password">
                    </div>
                    <input type="hidden" name="next" value="{{ request.path }}">
                </div>
                {% if form.errors %}
                    <p style="color:red">Invalid credentials!!!</p>
                {% endif %}
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Sign In</button>
        </div>
</form>

{% block javascript_code %}

{% if form.errors %}
    <script>
    $(function() {
      $('#modalSignIn').modal({show: true});
    });
    </script>
{% endif %}

{% endblock %}

CarnivalProject/accounts/templates/accounts/manageAccount.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block title %}Manage Account {% endblock %}

{% block content %}

<div class="container">
    <h1>Manage Account</h1>
    <p style="padding:20px"></p>
    <form method="POST" action="" class="form-horizontal" role="form">{% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-2 control-label">
                    {% bootstrap_label field.label %}
                </div>
                <div class="col-sm-4">
                    {% bootstrap_field field show_label=False required=False form_group_class=None placeholder="" %}
                </div>
            </div>
            <p style="padding:10px;"></p>
        {% endfor %}

        {% buttons %}
        <div class="col-sm-offset-4 col-sm-2">
            <button type="submit" class="btn btn-md btn-primary">Save</button>
        </div>
        {% endbuttons %}
    </form>
    <p style="padding:25px"></p>
</div>

{% endblock %}

CarnivalProject/accounts/templates/accounts/signUp.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block title %}Sign Up {% endblock %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <p style="padding:20px;"></p>
    <form method="POST" class="form-horizontal" role="form">{% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-2 control-label">
                    {% bootstrap_label field.label %}
                </div>
                <div class="col-sm-4">
                    {% bootstrap_field field show_label=False form_group_class=None placeholder="" %}
                </div>
            </div>
            <p style="padding:10px;"></p>
        {% endfor %}

        {% buttons %}
        <div class="col-sm-offset-4 col-sm-2">
            <button type="submit" class="btn btn-md btn-primary">Sign Up</button>
        </div>
        {% endbuttons %}
    </form>
</div>
<div>
    <p style="padding:25px"></p>
</div>

{% endblock %}